[build]
builder = "nixpacks"

[deploy]
startCommand = "npx serve -s dist -l $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[redirects]]
source = "/(.*)"
destination = "/index.html"
status = 200
